log_level: debug
project_name: example-project
pubsub:
  instance_creation_subscription_name: sie-creation-subscription
  instance_interruption_subscription_name: sie-interruption-subscription
prometheus:
  port: 8090
  path: /metrics
