apiVersion: apps/v1
kind: Deployment
metadata:
  name: -deployment
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: spot-interruption-exporter-sa
      securityContext:
        fsGroup: 65534
        runAsUser: 37100
        runAsGroup: 37100
      containers:
        - name: spot-interruption-exporter
          image: spot-interruption-exporter
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"
            limits:
              memory: "250Mi"
              cpu: ".5"
          envFrom:
            - configMapRef:
                name: terminator-config
          ports:
            - containerPort: 8090
              name: metrics
