apiVersion: apps/v1
kind: Deployment
metadata:
  name: -deployment
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: spot-interruption-exporter-sa
      securityContext:
        fsGroup: 65534
        runAsUser: 37100
        runAsGroup: 37100
      volumes:
        - name: app-config
          configMap:
            name: -configmap
      containers:
        - name: spot-interruption-exporter
          image: spot-interruption-exporter
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"
            limits:
              memory: "250Mi"
              cpu: ".5"
          volumeMounts:
            - name: app-config
              mountPath: /etc/config
          env:
            - name: "CONFIG_PATH"
              value: "/etc/config/config.yaml"
          ports:
            - containerPort: 8090
              name: metrics
