apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spot-interruption-exporter
namePrefix: spot-interruption-exporter
images:
  - name: spot-interruption-exporter
    newName: ghcr.io/thought-machine/spot-interruption-exporter
    newTag: sha-5543ca4

commonLabels:
  name: spot-interruption-exporter
  app: spot-interruption-exporter
  project: spot-interruption-exporter

configMapGenerator:
  - name: -configmap
    behavior: replace
    files:
      - config.yaml

resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
