apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spot-interruption-exporter
namePrefix: spot-interruption-exporter
commonLabels:
  name: spot-interruption-exporter
  app: spot-interruption-exporter
  project: spot-interruption-exporter

configMapGenerator:
  - name: -configmap
    behavior: replace
    files:
      - config.yaml

resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml