apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: -sm
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - spot-interruption-exporter
  selector:
    matchLabels:
      app: spot-interruption-exporter
