run:
  timeout: 5m
  skip-dirs:
    - test_data
    - mocks

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocritic

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - tenv
    - thelper
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - errcheck
    - exportloopref

linters-settings:
  govet:
    enable-all: true
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/thought-machine/please)
