project_name: tm-gcp-emea-build-infra
pubsub:
  instance_creation_subscription_name: sie-creation-subscription
  instance_interruption_subscription_name: sie-interruption-subscription
prometheus:
  port: 1111
  path: /bespoke-metrics-path