apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: custom-namespace

configMapGenerator:
  - name: -configmap
    behavior: replace
    files:
      - config.yaml

patches:
  - path: sa-patch.yaml

resources:
  - git@github.com:thought-machine/spot-interruption-exporter.git//kustomize
