name: Unit tests, lint, and build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Download mockery
        uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: "mockery"
          version: "v2.39.1"
          download_url: "https://github.com/vektra/${binary}/releases/download/${version}/mockery_${version}_Linux_x86_64.tar.gz"

      - name: Generate
        run: go generate -v ./...

      - name: Test
        run: go test -v ./...

      - name: Lint
        run: pre-commit run --all-files
